export const footballers = [
  {
    id: 0,
    name: 'Cristiano Ronaldo',
    age: 41,
    position: 'Forward',
    club: 'Al Nassr',
    country: 'Portugal',
  },
  {
    id: 1,
    name: 'Lionel Messi',
    age: 39,
    position: 'Forward',
    club: 'Inter Miami CF',
    country: 'Argentina',
  },
  {
    id: 2,
    name: 'Neymar Jr.',
    age: 34,
    position: 'Forward',
    club: 'Santos FC',
    country: 'Brazil',
  },
  {
    id: 3,
    name: 'Kylian Mbappé',
    age: 27,
    position: 'Forward',
    club: 'Real Madrid',
    country: 'France',
  },
  {
    id: 4,
    name: 'Toni Kroos',
    age: 36,
    position: 'Midfielder',
    club: 'Retired',
    country: 'Germany',
  },
  {
    id: 5,
    name: 'Erling Haaland',
    age: 23,
    position: 'Forward',
    club: 'Manchester City',
    country: 'Norway',
  },
]